


Dim Shared 命名空间 As 命名空间信息

Dim Shared 库接口 As 库接口信息

ReDim Shared 引用目录(Any) As String

Dim Shared 对象池 As HashPool
Dim Shared 容器池 As HashPool
Dim Shared 栈池 As HashPool

redim shared 库表(Any) as 库信息类型 ptr

Dim Shared 命名空间_lang As 命名空间信息 Ptr

Dim Shared 类_object As 类指向
Dim Shared 类_byte As 类指向
Dim Shared 类_short As 类指向
Dim Shared 类_int As 类指向
Dim Shared 类_long As 类指向
Dim Shared 类_float As 类指向
Dim Shared 类_double As 类指向
Dim Shared 类_bool As 类指向
Dim Shared 类_string As 类指向

Dim Shared 类_构造_object As 方法指向
Dim Shared 类_构造_byte As 方法指向
Dim Shared 类_构造_short As 方法指向
Dim Shared 类_构造_int As 方法指向
Dim Shared 类_构造_long As 方法指向
Dim Shared 类_构造_float As 方法指向
Dim Shared 类_构造_double As 方法指向
Dim Shared 类_构造_bool As 方法指向
Dim Shared 类_构造_string As 方法指向

Dim Shared 类_Array As 类信息
Dim Shared 类_Array_析构方法 As 函数信息

Dim Shared 类_CallBack As 类信息
Dim Shared 类_CallBack_析构方法 As 函数信息

Dim Shared 静态构造方法表(Any) As 函数信息 Ptr

Dim Shared 缓冲代大小 As Integer
Dim Shared 幸存代大小 As Integer
Dim Shared 老年代大小 As Integer

Dim Shared 缓冲代 As HashPool
Dim Shared 幸存代 As HashPool
Dim Shared 老年代 As HashPool

Dim Shared GCRoots As HashPool


